### ISSUE TITLE
Roadmap to develop image sharing on the host with integrity for CoCo

### ISSUE THREAD

**Issue by ChengyuZhu6** [confidential-containers/community#142]
Image sharing on the host with integrity was proposed in https://github.com/confidential-containers/confidential-containers/issues/137.  This issue is used to track the development of image sharing on the host with integrity for CoCo.

snapshotter:
- [x]  Export image as block device(s) with verity and return `Mount` array
https://github.com/containerd/nydus-snapshotter/pull/499
https://github.com/containerd/nydus-snapshotter/pull/530

kata-runtime/kata-agent:
- [x]  Support `tarfs` disk image to share data from host to guest
https://github.com/kata-containers/kata-containers/pull/7106
https://github.com/kata-containers/kata-containers/pull/7688

kata-rootfs:
- [x]  Install the dependencies with dm-verity
https://github.com/kata-containers/kata-containers/pull/7601

image-rs:
- [x]  Integrity check with dm-verity and mount the data
confidential-containers/guest-components/pull/270

tests:
- [x] tests for image sharing on the host
https://github.com/kata-containers/tests/pull/5764

The roadmap & task list can be updated then.

**Comment by huoqifeng** [comment]
@ChengyuZhu6 I don't see tasks related with `pulling image within guest` via remote snapshotter, is that scenario also covered by this story?

**Comment by ChengyuZhu6** [comment]
> @ChengyuZhu6 I don't see tasks related with `pulling image within guest` via remote snapshotter, is that scenario also covered by this story?
@huoqifeng No, It's just sharing image on the host.

**Comment by huoqifeng** [comment]
> > @ChengyuZhu6 I don't see tasks related with `pulling image within guest` via remote snapshotter, is that scenario also covered by this story?
> > @huoqifeng No, It's just sharing image on the host.

Is there an issue to track status for `pulling image within guest`, or shall it be created also?

**Comment by ChengyuZhu6** [comment]
> 

No, there is no issue to track `pulling image within guest`. I think it should be created separately.

**Comment by huoqifeng** [comment]
I guess which is part of the design agreed in https://github.com/confidential-containers/confidential-containers/issues/137 and I think we want all parts enabled in coming CoCo release(s). Do you mind to create such a story also to track that work as you might be more familiar with what remote-snapshoter/image-rs changes needed. Thank you! @ChengyuZhu6 @jiangliu

**Comment by wainersm** [comment]
Hi @ChengyuZhu6 , I'm trying to understand the testing requirements for the Kata's CCv0 -> main branches merge. Currently we got a few tests (see https://docs.google.com/document/d/14g38GK78wR32VsCume9KcMrBZLQMPrYMtBpdmcVpEZM/edit#bookmark=id.485f6ootzjvu) for the `image pulling from guest` feature. IIUC the `image sharing on host with integrity` should have a complete different set of tests. Am I right? If so, can we start discussing how those tests should look like and include them on this roadmap?

**Comment by ChengyuZhu6** [comment]
> Hi @ChengyuZhu6 , I'm trying to understand the testing requirements for the Kata's CCv0 -> main branches merge. Currently we got a few tests (see https://docs.google.com/document/d/14g38GK78wR32VsCume9KcMrBZLQMPrYMtBpdmcVpEZM/edit#bookmark=id.485f6ootzjvu) for the `image pulling from guest` feature. IIUC the `image sharing on host with integrity` should have a complete different set of tests. Am I right? If so, can we start discussing how those tests should look like and include them on this roadmap?

Hi @wainersm. Currently, `image sharing on host with integrity` only supports sharing unencrypted images. But unlike `image pulling from guest`, the shared images would be transformed into one or more disk images through the remote snapshotter(nydus -snapshotter or tardev-snapshotter). And we will support both  `image sharing on host with integrity` and  `image pulling from guest` to avoid using forked containerd(https://github.com/confidential-containers/confidential-containers/issues/146). So the main difference between the two parts may lie in two aspects: 1. the configuration in the remote-snapshotter to determine whether to share images or download images in the guest; 2. test unencrypted images only on `image sharing on host with integrity`. And I'm working on installing `remote-snapshotter` in the kata to support the tests.
