### ISSUE TITLE
CI/CD plan for CCv1

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/community#2]
**Context**

Currently we got [CI pipelines](http://jenkins.katacontainers.io/view/CCv0/) to test pull requests addressed to our CC branch of the Kata Containers project, however those are tests that ensure we don't introduce regressions to the "normal" Kata containers. As part of CCv1 proposal, we are aiming to delivery a "CI/CD (...) With and without a TEE, add confidential container integration tests" (slide 5) so that we begin catching CC specific regressions. This work will be particularly valuable for checking the rebases that Steve Horsman (and others) frequently carry out on our CC branch in the Kata Containers.  

**Deliverables**

 * Specific integration tests without TEE
 * Specific integration tests with TEE
 * CI pipelines

**Scope**
 * The CI pipelines will run for pull requests (PR) opened to the [kata-containers](https://github.com/kata-containers/kata-containers) and [tests](https://github.com/kata-containers/tests). Other repositories like [image-rs](https://github.com/confidential-containers/image-rs) and [attestation-agent](https://github.com/confidential-containers/attestation-agent) are out of the scope.
 * Test with containerd CRI
 * Test with Kubernetes + Containerd
 * CRI-O is out of scope
 * Use QEMU and Cloud Hypervisor as Kata hypervisor. Other hypervisors are out of scope for now 

**Assumptions**
 * The Kata CI resources (Jenkins and VMs on Azure) can be used.

**Risks**
 * Currently CC is developed in a branch of Kata Containers and [it is discussed its merge into `main`](https://github.com/kata-containers/tests/issues/4441). While that effort is important and the way to go, it might cause changes on this CI plans.
 * We aim to introduce the CC specific tests on Kata Container's tests repository and leverage the current Kata CI infrastructure and framework. This will turn CC tests/CI intimately coupled in Kata Containers, which goes against the aim of decouple Kata Containers and CC (being the former just a dependency of CC).

**Environments**
 * Ubuntu 20.04 (x86_64) VM - non-TEE tests
 * Fedora 35 (x86_64) VM - non-TEE tests
 * TEE tests - to be defined

**Major Milestones**
 1. February 2022: **Initial CI - all CC PRs go through CC specific integration tests**
 2. April 2022: **TEE (At least one) backed CI**

**Work items**

 **February, 2022**

- [ ] PoC: running a specific integration test without TEE
- [ ] Identify and detail more non-TEE tests
- [ ] Identify hardware requirements for TEE tests 

**March, 2022**
- [ ] Implement the remaining non-TEE tests
- [ ] Create non-TEE CI pipelines
- [ ] Onboard hardware for TEE tests
- [ ] Identify and detail TEE tests (mid-March)

**April, 2022**

- [ ] Implement TEE tests
- [ ] Create TEE CI pipelines
 
**The team**

The list of people who will be involved on this CI effort:

| Contact | Role |
| ---------- | ------- |
| Wainer Moschetta (@wainersm), Red Hat | Developer - QEMU tests and CI pipelines |
|Agam Dua, Apple | Developer - Cloud Hypervisor |
| Peter(@peterzcst )/Arron(@arronwy )  | Hardware owner -  Intel TDX TEE |
| Unmesh Deodhar, AMD | Hardware owner - AMD SEV / Tests SEV|
| Hendrik Brueckner (@hbrueckner) | Hardware owner - IBM s390x/Secure Execution |

**Comment by peterzcst** [comment]
hi @wainersm , please my latest comments in #4.  We are ready to integrate first TDX pipeline using CCV0+Qemu+TDVF in CCV0 CI. So please help task of "Add Intel TDX machine in the CC CI pool" for April

**Comment by wainersm** [comment]
> hi @wainersm , please my latest comments in #4. We are ready to integrate first TDX pipeline using CCV0+Qemu+TDVF in CCV0 CI. So please help add task of "Add Intel TDX machine in the CC CI pool" for April deliverable

Hi @peterzcst , just created the issue https://github.com/confidential-containers/community/issues/32 to track that work.

**Comment by wainersm** [comment]
Delivered on 1st release.
