### ISSUE TITLE
Roadmap from removing skopeo - image-rs signature verification gap for the first release

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/community#57]
On the Confidential containers call on 4th August there was a discussion about what we had remaining to cut the first release. This mostly came down to creating an e2e CI/CD process for the operator and the removal of skopeo, which this issue is going to talk about.

### Current status

At the moment we have some Kata CI signature verification tests, but they only work when skopeo is installed in the Kata guest. We also have the get_resource endpoint implementation for the `sample_kbc` in the `attestation-agent`, but there aren't any integration tests of this yet to show/test how it works with image-rs. It sounds like this kbc implementation, should be very similar to the `offline_fs_kbc` that we want to implement as that's what our Kata CC CI/CD pipeline uses at the moment, so it's a good base to start from.

There is also the gap of skopeo supporting authenticated container registries, which we can't currently do with image-rs in and e2e scenario, but that's part of [kata-containers/kata-containers#4601](https://github.com/kata-containers/kata-containers/issues/4601) and not been agreed and broken down to the same detail yet.

### Goal

Our goal for the first release (with respected to signature verification), is to get the Kata CC tests of signature verification using local attestation working without skopeo needing to be installed in the guest image and then remove the skopeo and umoci binaries from the operator payload.

### Roadmap for achieving this

This is my proposed path of how we can get to the goal. I'm still fleshing out the detail on some of the issues, but feel free to add comments or questions:

- [ ] https://github.com/confidential-containers/image-rs/issues/43
- [ ] https://github.com/confidential-containers/attestation-agent/issues/63
- [ ] https://github.com/confidential-containers/image-rs/issues/44
- [ ] https://github.com/kata-containers/kata-containers/issues/4581
- [ ] https://github.com/kata-containers/kata-containers/issues/4888
- [ ] https://github.com/kata-containers/kata-containers/issues/4889

At this point I think we've met the MVP of removing and testing the skopeo - image-rs gap of support signature verification e2e, but there are some further things we might like to do
- [ ] https://github.com/kata-containers/kata-containers/issues/4601 - this addresses the other skopeo gap we currently know about
- [ ] https://github.com/confidential-containers/cloud-api-adaptor/issues/164
- [ ] https://github.com/kata-containers/kata-containers/issues/3970
- [ ] **Think about whether we can merge the `offline_fs_kbc` and `sample_kbc`** - As a longer term item I think it's worth trying to work out what the difference between the two (or more) local attestation kbcs is and whether we can/should merge them together rather than duplicating the code, but lets get them to work first and worry about this post release.

**Comment by ariel-adam** [comment]
@stevenhorsman is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by stevenhorsman** [comment]
It's worth noting that we have at least one defect/gap between skopeo and image-rs:
- https://github.com/confidential-containers/image-rs/issues/82 
so we need to decide if these are blockers to remove skopeo support, or somethings we can mitigate
