### ISSUE TITLE
Roadmap for Generic Key Broker System in v0.5.0 release.

### ISSUE THREAD

**Issue by jialez0** [confidential-containers/community#68]
Up to now, in v0.2.0 release, we have two experimental Key Broker Systems for CoCo: `online_sev_kbc - simple kbs` for SEV and `eaa_kbc - verdictd` for TDX, which have been included in the [Release Note](https://github.com/confidential-containers/documentation/blob/main/releases/v0.1.0.md) for user deployment, can support providing the required confidential data for [`image-rs`](https://github.com/confidential-containers/image-rs) (such as the key required to decrypt the container image). However, both KBS above are now specific on HW-TEE architecture, and they are incomplete solutions using their own KBC-KBS interaction protocol. In addition, `verdictd` relies on some external components and is complex in configuration and deployment.

So just like we discuss before in (https://github.com/confidential-containers/documentation/issues/30) (Most of the contents are outdated). We need a standard and generic KBS, which is compatible with multi-architecture HW-TEE, full stack implementation of Rust, and neutral and completely owned by CoCo. It will be an out-of-the-box productive KBS component in the CoCo solution.

Now, we plan to release our Generic Key Broker System in **v0.5.0**, including the following components:

- `cc-kbc` of [Attestation Agent](https://github.com/confidential-containers/attestation-agent)
- [Key Broker Service](https://github.com/confidential-containers/kbs) (KBS for short)
- [Attestation Service](https://github.com/confidential-containers/attestation-service/) (AS for short)

### Goal

In v0.5.0 release, we hope generic KBS-AS become the default Key Broker System recommended by CoCo solutions, while `simple kbs` and `verdictd` are provided as optional customized implementations.

### Architecture

Here is the architecture of generic Key Broker System (`cc-kbc`, KBS, AS):

![kbs](https://user-images.githubusercontent.com/35883144/202992147-5c638b7b-11fb-4ee9-8285-c2a53c65fc40.png)

According to the architecture, we can divide the work into four parts: `cc-kbc`, KBS, AS, Reference value publish.

### Current Status

Up to now we have already made some progress on our generic Key Broker System, we have defined the generic protocol between `cc-kbc` and KBS, `cc-kbc` now is support that protocol, and AS framework part is ready now. But there is still a gap from where the entire system can be used.

### Roadmap for achieving the goal

This is my proposed path of how we can get to the goal. I'm still fleshing out the detail on some of the issues, but feel free to add comments or questions:

#### Attestation Agent
* [ ] https://github.com/confidential-containers/attestation-agent/issues/102
* [ ] https://github.com/confidential-containers/attestation-agent/issues/108
* [ ] https://github.com/confidential-containers/attestation-agent/issues/59
* [ ] https://github.com/confidential-containers/attestation-agent/issues/109

#### KBS
* [ ] https://github.com/confidential-containers/kbs/issues/16
* [ ] https://github.com/confidential-containers/kbs/issues/17
* [ ] https://github.com/confidential-containers/kbs/issues/18

#### Attestation Service
* [ ] https://github.com/confidential-containers/attestation-service/issues/11
* [ ] https://github.com/confidential-containers/attestation-service/issues/7
* [ ] https://github.com/confidential-containers/attestation-service/issues/30

#### Reference measurement value provide
When building Github Action, we need to provide the interface for RVPS (Reference Value Provider Service) in AS to subscribe reference value of component measurement, including kernel, kernel parameters and root file system. (This is an enhanced part. Before it is ready, we can temporarily manually send the reference value of measurement to RVPS. For more details on this part of the work, @Xynnn007 may can give some proposals.

**Comment by Xynnn007** [comment]
Thanks for the great plan for remote attestation overview of CC! I'll open another issue to describe the measurement-related roadmaps later.

**Comment by fitzthum** [comment]
This is great. Excited to help out.

**Comment by sameo** [comment]
Very nice. Thanks for putting this together!

**Comment by jxyang** [comment]
I like the idea of abstracting out attestation service. Have you thought about using a cloud attestation service like [Microsoft Attestation Service](https://learn.microsoft.com/en-us/rest/api/attestation/attestation/attest-sev-snp-vm?tabs=HTTP)? It is designed to abstract out specific HW TEEs and provide a unified attestation flow. It supports SGX and SNP already.

Given a SNP/SGX attestation report, MAA returns a token after validating the report, which is signed by a private key. KBS can then validate the token with a well-known public key.

By offloading the AS to cloud, we could reduce the footprint of guest VM and maintenance cost. Of course, the down side is that we have to include the cloud attestation service in the TCB. Our experience indicates some customers don't mind that.

**Comment by surajssd** [comment]
@jxyang a similar suggestion has been raised here: https://github.com/confidential-containers/cloud-api-adaptor/issues/379

**Comment by jxyang** [comment]
@surajssd Thanks. I made a comment there too.

**Comment by jialez0** [comment]
> btw @jialez0 Will the KBS be multi-tenant?

What do you mean by multi tenant support? Yes or No: KBS creates different User instances. The instances include the Key and Secret resource storage of the User, and the AS using the User's Attest Policy. This requires AA to carry the User ID when requesting KBS to indicate which User instance KBS uses to process the request. Is my understanding accurate?

I think this mechanism is reasonable and necessary, but we need to think about three issues:

1. `User ID` or `TEE instance ID`: In the above scheme, resources and policies are divided according to the granularity of the User. The essential purpose is to differentiate TEE instances through the user. Should we go further and directly divide resources and policies in the granularity of the TEE instance?

2. What does AA use to represent ID? This is a key problem. Maybe we can use some existing information to represent this ID, or we can design a new one.

3. How to register an ID in KBS and ensure that AA can know which ID its environment belongs to?

These issues deserve more discussion. Perhaps a new issue should be opened at KBS to discuss them?

**Comment by jialez0** [comment]
> Also, are we planning to use HTTPS like the spec mentions?

Yes, we need HTTPS. This allows AA to authenticate the identity of KBS (although how to pass the certificate is still under discussion)...

**Comment by jialez0** [comment]
> Given a SNP/SGX attestation report, MAA returns a token after validating the report, which is signed by a private key. KBS can then validate the token with a well-known public key.

You can see that in our current KBS protocol design, KBS can also support issuing its own Token. If the `/auth` request carries this token and the verification passes, KBS can skip the subsequent `Challenge` and `Attestation` phases. Therefore, KBS can easily add verification support for Tokens signed by other trusted third parties (such as MAA Tokens), which can be implemented as an enhancement.

**Comment by fitzthum** [comment]
@jialez0 

> What do you mean of multi tenant supporting? Does it meas: KBS creates different User instances. The instances include the Keys and Secrets resource storage of the User, and the AS using the User's Attest Policy. This requires AA to carry the User ID when requesting KBS to indicate which User instance KBS should uses to process the request. Is my understanding accurate?

Yes. I agree with the issues you point out. It seems hard for the KBS to be sure that they are deploying the correct secrets to a given user, especially given that the attestation reports for each user would probably be the same.

**Comment by jxyang** [comment]
@jialez0 Great to know that the design allows 3rd-party tokens. Do you mind making it clear in the above diagram?

**Comment by sameo** [comment]
> > Also, are we planning to use HTTPS like the spec mentions?
> 
> Yes, we need HTTPS. This allows AA to authenticate the identity of KBS (although how to pass the certificate is still under discussion...).
> 
> cc @sameo

See https://github.com/confidential-containers/kbs/pull/19 for the WIP PR of the api server implementation. It is based on actix for the HTTP side and we will make HTTPS mandatory.

**Comment by Xynnn007** [comment]
Hi, for measurement-reference issues, we made a proposal to provide reference values. https://github.com/confidential-containers/attestation-service/issues/42 Anyone interested in this please take some time to help review. :)

**Comment by zvonkok** [comment]
Will this architecture also support 3rd party artifacts? Meaning customers bring their own guest-os, kernel, and reference values that could be attested in a later step, layered, composite attestation?

**Comment by Xynnn007** [comment]
> Will this architecture also support 3rd party artifacts? Meaning customers bring their own guest-os, kernel, and reference values that could be attested in a later step, layered, composite attestation?

Yes, certainly. The key point is the reference values used in comparation with evidences could be set by the users themselves in RVPS or OPA policy filter, both in AS.

**Comment by zvonkok** [comment]
I assume a 3rd party KBS will also be supported?

**Comment by zvonkok** [comment]
I assume a 3rd party KBS will also be supported?

**Comment by zvonkok** [comment]
What about the use-case of extending the attestation report? We may have the situation where another entity creates an attestation report inside the TEE; it would be nice if we could also attest this in a second step or in an accumulated attestation report with accumulated reference values or different reference values.

**Comment by zvonkok** [comment]
verdictd does have support for remote KBS, AFAIK.

**Comment by zvonkok** [comment]
Once TDISP/IDE is available if will be natural that TEEs have trusted accelerators that provide their own attestation reports, independently of the Kata stack, well even now with bounce buffers there is demand for accelerator attestation in our use-case.

**Comment by jialez0** [comment]
> I assume a 3rd party KBS will also be supported?

The third-party KBS can indeed be supported. Now the Verdictd and simple KBS in coco release are actually third-party KBS. They connect with CoCo through the exclusive KBC module in the Attestation Agent.

**Comment by fitzthum** [comment]
@zvonkok 

> What about the use-case of extending the attestation report? We may have the situation where another entity creates an attestation report inside the TEE; it would be nice if we could also attest this in a second step or in an accumulated attestation report with accumulated reference values or different reference values.

Getting a second report inside the guest, probably as part of the workload, is interesting. We have to be careful about how we do this to avoid creating security problems, but it should be possible. I am generally thinking that a workload would use this report to connect to some other service that wants to consume an attestation report (rather than connecting to our KBS again). Did you have anything specific in mind?

> Once TDISP/IDE is available if will be natural that TEEs have trusted accelerators that provide their own attestation reports, independently of the Kata stack, well even now with bounce buffers there is demand for accelerator attestation in our use-case.

We should think about the best way to support this. The easiest way would be to modify our verifiers to call out to some vendor-specific plugins that know how to verify devices. Maybe we should try to come up with something more flexible, though. Some form of composable attestation that allows verifiers to consume each other.

**Comment by zvonkok** [comment]
@fitzthum You're on the right track where I am heading. Yes, this architecture needs to be more flexible. Let's make it more concrete and introduce our use cases with confidential containers. 

For the seamless running of GPU workloads on Kata we're packaging the driver and the toolkit (for container enablement, prestart hook) in the guest, which means customers do not see any difference when running GPU workloads with or without Kata. 

`ctr run <whatever>` is the very same. 

For this to work we're shipping an custom build of the kernel, guest-os and several GPU-kata-runtimes. So it's a mix of standard components (e. g. OVMF) and additional components that are provided by a 3rd party. In the case of Kubernetes the GPU-operator will pull down the needed parts from repository (signed and encrypted) only if the base install of a confidential container can run and attested (without GPU). 

Once we fire up a GPU confidential-container we would like to attest the old components and new components with our supplied reference values. Meaning the KBS needs to provide a way to supply our own policy files. 

To make the attestation workload agnostic, the idea was to have a component in the guest-os that retrieve the attestation report and provide it to an external entity like the KBS that then does the attestation with additional reference values, maybe something like  a two step approach, First attest the base stack and second attest additional attestation reports that are supplied. 

It does not stop there, what if we have multiple accelerators? Do we concat the attestation reports and do one by one attestation and just "disable" the not successfully attested devices? Or do we do a verification over all devices all at once? 

It would be nice if we could do several rounds of attestation by providing a set of attestation-report, policies, and reference values on demand even during runtime at "any" time. 

In the case of Kubernetes, we're relying on the GPU operator to provide the configuration (enable SR-IOV, create VFs, etc) and the needed artifacts to enable GPUs in Kata, aka CoCo. 

External entities should be able to retrieve attestation results or request attestation of a specific configuration. The GPU operator cannot attest itself; some higher level entity needs to do that, like in the case of SNP where the SP is providing the attestation report and CoCo attests the environment with the provided policies and ref. values. 

There needs to be a terminal entity which the workload trusts a general interface to get the chained results of attestations for the complete stack. This terminal entity cannot be CoCo because you would have higher-level entities that are introducing HW, SW that needs to be attested in a specific "way", in other environments not specifically tied to CoCo. 

You we're right when saying the "workload would use this report to connect to some other service" but to which service it connects, depends on how your stack looks like.

**Comment by zvonkok** [comment]
@fitzthum Are we looking into https://www.ietf.org/archive/id/draft-ietf-rats-architecture-22.html as well as a reference?

**Comment by yaoxin1995** [comment]
@fitzthum @jialez0 

I am integrating the KBS to [quark runtime](https://github.com/yaoxin1995/master-thesis-quark/tree/working)  following the kbs attestation protocol.  

I have a few questions.

1. Will 1 KBS instance only be owned by 1 data owner and only contain secrets belonging to 1 party? Or multiple data owners can share 1 KBS instance?

2.  Where does the KBS run? Will it run on the data owner's side or will it run also in a secure VM hosted in the public cloud like the enclave?  In the latter case, the data owner needs to ensure the KBS running in an expected environment before uploading the secret, how do we achieve this?

3.  KBS attestation protocol uses tls to avoid malicious attackers from hijacking KBS address to impersonate KBS and deceive KBC. In turn, how does the KBS prevent malicious attackers from impersonating KBC to get the secret from it?  

For example,  assume KBS only contains secrets from 1 party and We have KBS instant A that stores the secret from a  data owner.  Now the data owner and attacker deploy an Nginx service each,  using the same image. In this case, both services may generate the same attestation report, which means both services are able to get the secret from the KBS.    However, KBS should only provide the secret to the Nginx service deployed by the data owner. So how can the KBS be sure that they are deploying the secrets to the correct user?

**Comment by fitzthum** [comment]
@yaoxin1995 
> 
> I am integrating the KBS to [quark runtime](https://github.com/yaoxin1995/master-thesis-quark/tree/working) following the kbs attestation protocol.
> 
Cool
> I have a few questions.
> 
>     1. Will 1 KBS instance only be owned by 1 data owner and only contain secrets belonging to 1 party? Or multiple data owners can share 1 KBS instance?
> 
The KBS is trusted, but there are potentially multiple ways for it to operate. The simplest is that each client will run their own KBS that serves only their secrets. You could also run a KBS as a service and either provide separate virtualized KBS instances to clients or serve multiple clients with one KBS (not really supported with this codebase yet). In any case the KBS must be trusted.

>     2. Where does the KBS run? Will it run on the data owner's side or will it run also in a secure VM hosted in the public cloud like the enclave?  In the latter case, the data owner needs to ensure the KBS running in an expected environment before uploading the secret, how do we achieve this?
> 
Again, the simplest case is for the client to deploy the KBS themselves somewhere that they trust, but more complex arrangements are possible. A KBS could run inside of a TEE either operated by the client or by a CSP. Unless the client has a reason to trust the CSP, this TEE would need to be attested, which might require another KBS. Having two levels of KBS might seem redundant, but it could be useful. The client would only have to attest the KBS running in a TEE once. Then that KBS could handle many confidential guests.

>     3. KBS attestation protocol uses tls to avoid malicious attackers from hijacking KBS address to impersonate KBS and deceive KBC. In turn, how does the KBS prevent malicious attackers from impersonating KBC to get the secret from it?
> 
The KBS identifies the KBC based on the attestation evidence. The content of the attestation evidence and the guarantees that it provides are implementation dependent. Confidential Containers uses generic guest images, meaning that the attestation evidence does not uniquely identify a guest. Rather, the evidence certifies that the guest is some valid Confidential Containers guest that the KBS can inject an identity into. I'm not sure what your goal with Quark will be.

> For example, assume KBS only contains secrets from 1 party and We have KBS instant A that stores the secret from a data owner. Now the data owner and attacker deploy an Nginx service each, using the same image. In this case, both services may generate the same attestation report, which means both services are able to get the secret from the KBS. However, KBS should only provide the secret to the Nginx service deployed by the data owner. So how can the KBS be sure that they are deploying the secrets to the correct user?

Generic workloads can be confusing for people. First of all, note that for CoCo the attestation report is the same for most guests, regardless of the pod that is deployed. For CoCo restrictions on the workload are enforced via signatures. You might be doing something else with Quark, but for now let's just update your example to use signatures. The following is still true if you don't use signatures and just put the measurement of the container in the attestation report.

Using signatures the KBS would be provisioned with a signature policy that allows a container to run. The KBS will only send secrets to workloads that meet this signature check. The only workloads that a KBS should allow to run via signatures are workloads that the KBS will trust with its secrets. A KBS will only trust a workload with a secret if the workload won't reveal the secret to any other parties. If this is the case, it really doesn't matter if the workload is generic or if it was started on behalf of the client or some malicious party.

Nginx is a misleading example because secrets provided to an nginx container probably could be exfiltrated via HTTP. So a KBS should never really provide secrets to a stock nginx container. Let's imagine instead that we have a hardened container that receives a secret and does some computations. The secret can never leave the container. In this case, it doesn't matter  who actually starts the container.

Hopefully that helps. You might also check out this [gist](https://gist.github.com/fitzthum/f3124f846e6ecbc066c53c6d31668979).
